import 'package:get/get.dart';
class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "duedays": "Due days",
      "dashboard": "Dashboard",
      "menu": "Menu",
      "logout": "Logout",
      "about iclean": "About iClean",
      "before": "Before",
      "during": "During",
      "after": "After",
      "next cleaning date": "Next cleaning date",
      "last cleaned date": "Last cleaned date",
      "select language": "Select language",
      "are you sure you want to logout?": "Are you sure you want to logout?",
      "cancel": "Cancel",
      "scheduled Cleanings": "Scheduled Cleanings",
      "tanks are scheduled for cleaning every 15 days to maintain compliance. The app highlights tanks due for cleaning.": "Tanks are scheduled for cleaning every 15 days to maintain compliance. The app highlights tanks due for cleaning.",
      "overdue Notifications": "Overdue Notifications",
      "if tanks aren’t cleaned on time, the app shows indicators to alert users about overdue cleanings.": "If tanks aren’t cleaned on time, the app shows indicators to alert users about overdue cleanings.",
      "clean Status Tracking": "Clean Status Tracking",
      "each cleaning stage ('Before,' 'During,' 'After') is recorded with timestamps, images, and status icons, providing full transparency in the maintenance lifecycle.": "Each cleaning stage ('Before,' 'During,' 'After') is recorded with timestamps, images, and status icons, providing full transparency in the maintenance lifecycle.",
      "panchayat": "Panchayat",
      "union": "Union",
      "tank Capacity": "Tank Capacity",
      "no tank data available": "No tank data available",
      "upload":"Upload",
    },
    'ta_ES': {
      "duedays": "தவணை நாள்",
      "dashboard": "டாஷ்போர்டு",
      "menu": "மெனு",
      "logout": "வெளியேறு",
      "about iclean": "iClean பற்றி",
      "before": "வேலைக்கு முன்",
      "during": "வேலையின் போது",
      "after": "வேலைக்குப் பிறகு",
      "next cleaning date": "அடுத்து சுத்தம் செய்யும் தேதி",
      "last cleaned date": "கடைசியாக சுத்தம் செய்யப்பட்ட தேதி",
      "select language": "மொழியை தேர்ந்தெடுக்கவும்",
      "are you sure you want to logout?": "நிச்சயமாக வெளியேற விரும்புகிறீர்களா?",
      "cancel": "ரத்து செய்",
      "scheduled Cleanings": "திட்டமிடப்பட்ட சுத்தம்",
      "tanks are scheduled for cleaning every 15 days to maintain compliance. The app highlights tanks due for cleaning.": "இணக்கத்தை பராமரிக்க ஒவ்வொரு 15 நாட்களுக்கும் தொட்டிகளை சுத்தம் செய்ய திட்டமிடப்பட்டுள்ளது. பயன்பாடு சுத்தம் செய்ய வேண்டிய தொட்டிகளை முன்னிலைப்படுத்துகிறது.",
      "overdue Notifications": "காலாவதியான அறிவிப்புகள்",
      "if tanks aren’t cleaned on time, the app shows indicators to alert users about overdue cleanings.": "டாங்கிகள் சரியான நேரத்தில் சுத்தம் செய்யப்படாவிட்டால், காலதாமதமான சுத்தம் குறித்து பயனர்களை எச்சரிப்பதற்கான குறிகாட்டிகளை ஆப்ஸ் காட்டுகிறது.",
      "clean Status Tracking": "சுத்தமான நிலை கண்காணிப்பு",
      "each cleaning stage ('Before,' 'During,' 'After') is recorded with timestamps, images, and status icons, providing full transparency in the maintenance lifecycle.": "ஒவ்வொரு துப்புரவு நிலையும் ('வேலைக்கு முன்,' 'வேலையின் போது,' 'வேலைக்குப் பின்') நேர முத்திரைகள், படங்கள் மற்றும் நிலை சின்னங்களுடன் பதிவு செய்யப்படுகிறது, இது பராமரிப்பு வாழ்க்கைச் சுழற்சியில் முழு வெளிப்படைத்தன்மையை வழங்குகிறது.",
      "panchayat": "பஞ்சாயத்து",
      "union": "ஒன்றியம்",
      "tank Capacity": "தொட்டி கொள்ளளவு",
      "no tank data available": "தொட்டி தரவு இல்லை",
      "upload":"பதிவேற்றம்",
    },
    'hi_IN': {
      "duedays": "अवधि दिन",
      "dashboard": "डैशबोर्ड",
      "menu": "मेनू",
      "logout": "लॉगआउट",
      "about iclean": "iClean के बारे में",
      "before": "काम से पहले",
      "during": "काम के दौरान",
      "after": "काम के बाद",
      "next cleaning date": "अगली सफाई की तारीख",
      "last cleaned date": "अंतिम सफाई की तारीख",
      "select language": "भाषा चुनें",
      "are you sure you want to logout?": "क्या आप वाकई लॉगआउट करना चाहते हैं?",
      "cancel": "रद्द करें",
      "scheduled Cleanings": "निर्धारित सफाई",
      "tanks are scheduled for cleaning every 15 days to maintain compliance. The app highlights tanks due for cleaning.": "अनुपालन बनाए रखने के लिए हर 15 दिनों में टैंकों की सफाई का कार्यक्रम बनाया गया है। ऐप सफाई के लिए निर्धारित टैंकों को दिखाता है।",
      "overdue Notifications": "अतिदेय सूचनाएं",
      "if tanks aren’t cleaned on time, the app shows indicators to alert users about overdue cleanings.": "यदि टैंक समय पर साफ नहीं किए जाते हैं, तो ऐप अतिदेय सफाई के बारे में चेतावनी देने के लिए संकेतक दिखाता है।",
      "clean Status Tracking": "सफाई स्थिति ट्रैकिंग",
      "each cleaning stage ('Before,' 'During,' 'After') is recorded with timestamps, images, and status icons, providing full transparency in the maintenance lifecycle.": "प्रत्येक सफाई चरण ('काम से पहले', 'काम के दौरान', 'काम के बाद') को समय स्टैम्प, चित्रों और स्थिति आइकन के साथ दर्ज किया जाता है, जिससे रखरखाव जीवनचक्र में पूरी पारदर्शिता मिलती है।",
      "panchayat": "पंचायत",
      "union": "संघ",
      "tank Capacity": "टैंक क्षमता",
      "no tank data available": "कोई टैंक डेटा उपलब्ध नहीं",
      "upload": "अपलोड",
    },

  };
}
